jobs:
- job:
  displayName: Ubuntu
  pool:
    vmImage: ubuntu-latest
  variables:
    DISPLAY: ':99.0'
    PYVISTA_OFF_SCREEN: 'True'
  strategy:
    matrix:
      linux-Python37:
        python.version: '3.7'
      linux-Python38:
        python.version: '3.8'
      linux-Python39:
        python.version: '3.9'
      linux-Python310:
        python.version: '3.10'
  steps:

  - bash: echo '##vso[task.prependpath]$CONDA/bin'
    displayName: Add conda to PATH

  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: |
      eval "$(conda shell.bash hook)"
      conda update --yes --quiet -n base conda
      conda install --yes --quiet -c conda-forge mamba
    displayName: Install mamba

  - script: |
      eval "$(conda shell.bash hook)"
      echo "  - python="$(python.version) >> environment_test.yml
      mamba env create -f environment_test.yml
      conda activate test
      pip install pytest-azurepipelines
    displayName: Create Anaconda testing environment

  - bash: |
      eval "$(conda shell.bash hook)"
      conda activate test
      pip install -e .
    displayName: Install requirements and build
    condition: ne(variables['python.version'], '3.8')

  - bash: |
      eval "$(conda shell.bash hook)"
      conda activate test
      .ci/setup_headless_display.sh
      pytest -v -s --ignore=tests/docs -W ignore::DeprecationWarning
    displayName: 'Testing'
    condition: ne(variables['python.version'], '3.8')

  - bash: |
      eval "$(conda shell.bash hook)"
      conda activate test
      export DISC_COV=1
      pip install -e .
    displayName: Install requirements and build for Testing
    condition: eq(variables['python.version'], '3.8')

  - bash: |
      eval "$(conda shell.bash hook)"
      conda activate test
      .ci/setup_headless_display.sh
      pytest -v -s --cov-config=.coveragerc --cov=discretize --cov-report=xml --cov-report=html -W ignore::DeprecationWarning
    displayName: 'Testing with coverage'
    condition: eq(variables['python.version'], '3.8')

  - bash: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov
      chmod +x codecov
      ./codecov
    displayName: 'Upload coverage to codecov.io'
    condition: eq(variables['python.version'], '3.8')
