jobs:
- job:
  displayName: Mac
  pool:
    vmImage: macOS-latest
  strategy:
    matrix:
      osx-Python37:
        python.version: '3.7'
      osx-Python38:
        python.version: '3.8'
      osx-Python39:
        python.version: '3.9'
      osx-Python310:
        python.version: '3.10'
  steps:

  - bash: echo '##vso[task.prependpath]$CONDA/bin'
    displayName: Add conda to PATH

  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - bash: |
      eval "$(conda shell.bash hook)"
      conda update --yes --quiet -n base conda
      conda install --yes --quiet -c conda-forge mamba
    displayName: Install mamba

  - script: |
      eval "$(conda shell.bash hook)"
      echo "  - python="$(python.version) >> environment_test.yml
      mamba env create -f environment_test.yml
      conda activate test
      pip install pytest-azurepipelines
    displayName: Create Anaconda testing environment

  - bash: |
      eval "$(conda shell.bash hook)"
      conda activate test
      pip install -e .
    displayName: Install requirements and build

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      pytest -v -s --ignore=tests/docs -W ignore::DeprecationWarning
    displayName: 'Running Tests'
