jobs:
- job:
  displayName: Mac
  pool:
    vmImage: macOS-latest
  strategy:
    matrix:
      osx-Python37:
        python.version: '3.7'
      osx-Python38:
        python.version: '3.8'
      osx-Python39:
        python.version: '3.9'
      osx-Python310:
        python.version: '3.10'
  steps:

  - bash: echo '##vso[task.prependpath]$CONDA/bin'
    displayName: Add conda to PATH

  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - script: |
      eval "$(conda shell.bash hook)"
      conda update --yes --quiet -n base conda
      conda install --yes --quiet -n base -c conda-forge mamba
      mamba create --yes --quiet --name test python=$(python.version)
    displayName: Create Anaconda environment

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      mamba install --yes --quiet -c conda-forge numpy scipy matplotlib cython vtk pyvista pymatsolver pytest
      pip install -r requirements_dev.txt
      pip install pytest-azurepipelines
      pip install -e .
    displayName: Install requirements and build

  - script: |
      eval "$(conda shell.bash hook)"
      conda activate test
      pytest -v -s --ignore=tests/docs -W ignore::DeprecationWarning
    displayName: 'Running Tests'
